apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-postgres-cronjob
  namespace: demo
spec:
  schedule: "*/30 * * * *" # Her 30 dakikada bir çalışır
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-tester
            image: bitnami/postgresql:17.1.0
            env:
            - name: PGHOST
              value: "postgres-postgresql"
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: "postgres"
            - name: PGDATABASE
              value: "containers"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-postgresql
                  key: PGPASSWORD
            command: ["/bin/bash"]
            args:
            - "-c"
            - |
              echo "Testing PostgreSQL connection..."
              psql -h $PGHOST -p $PGPORT -U $PGUSER -d $PGDATABASE -c "\l" && \
              echo "Creating test table..." && \
              psql -h $PGHOST -p $PGPORT -U $PGUSER -d $PGDATABASE -c "CREATE TABLE IF NOT EXISTS test_table (id SERIAL PRIMARY KEY, name VARCHAR(50));" && \
              echo "Inserting data into test table..." && \
              psql -h $PGHOST -p $PGPORT -U $PGUSER -d $PGDATABASE -c "INSERT INTO test_table (name) VALUES ('Test Data');" && \
              echo "Querying test table..." && \
              psql -h $PGHOST -p $PGPORT -U $PGUSER -d $PGDATABASE -c "SELECT * FROM test_table;" && \
              echo "Dropping test table..." && \
              psql -h $PGHOST -p $PGPORT -U $PGUSER -d $PGDATABASE -c "DROP TABLE IF EXISTS test_table;" && \
              echo "PostgreSQL tests completed successfully!"
          restartPolicy: Never
      backoffLimit: 4
