apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
      name: http
    - port: {{ .Values.service.agentPort }}
      targetPort: 50000
      name: agent
  selector:
    {{- include "jenkins.selectorLabels" . | nindent 4 }}
