apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 0  # root olarak çalıştır
        fsGroup: 0
      containers:
      - name: jenkins
        image: jenkins/jenkins:2.414.2-lts
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: httpport
        - containerPort: 50000
          name: jnlpport
        securityContext:
          allowPrivilegeEscalation: true
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: demo
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32001
      name: http
    - port: 50000
      targetPort: 50000
      name: agent
  selector:
    app: jenkins
