apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: jenkins
 namespace: demo
spec:
 accessModes:
   - ReadWriteOnce
 storageClassName: local-storage
 resources:
   requests:
     storage: 8Gi
