postgresql:
 auth:
   existingSecret: postgres-secret
   secretKeys:
     adminPasswordKey: postgres-password
     userPasswordKey: password
   username: devops
   database: containers
 primary:
   service:
     type: NodePort
     nodePorts:
       postgresql: "30432"
   persistence:
     enabled: true
     size: 8Gi
