replicaCount: 1
image:
  repository: app
  tag: latest
  pullPolicy: Never
service:
  type: NodePort
  port: 8080
  nodePort: 30080
env:
  # PostgreSQL Environment Variables
  - name: POSTGRES_HOST
    value: "postgres-postgresql.demo.svc.cluster.local"
  - name: POSTGRES_PORT
    value: "5432"
  - name: POSTGRES_DB
    value: "containers"
  - name: POSTGRES_USER
    value: "postgres"
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-postgresql
        key: postgres-password
  # Redis Environment Variables
  - name: REDIS_HOST
    value: "redis-master.demo.svc.cluster.local"
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis
        key: redis-password
